---
title: "CORE121 Election Science Syllabus Fall 2021"
output:
  pdf_document:
    toc: no
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    toc_depth: 4
    self_contained: no
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warning = FALSE, errors = FALSE, message = FALSE, tidy = FALSE, cache = FALSE)
```

**CORE 121-01 and CORE121-11 Numbers: Election Science**  

Section 1 meets MWF at 11:30am - 12:30pm in JR Howard 115  
Section 11 meets MWF at 1:50pm - 2:50pm in JR Howard 253  
Lewis & Clark College  
Fall 2021  
 
Instructor: Ian McDonald, Ph.D.  
Email: ianmcdonald@lclark.edu  
Miller Hall 434  
+1.503.768.7456  

Office Hours:   
Tuesdays 9:30-11 am & Fridays 10-11am + email or additional times by schedule. You can meet with me in person or via teleconferencing.  

## Syllabus Links:
html: https://bit.ly/3DsSIgk
pdf: https://bit.ly/2WyzYea   

## Course Description

We expect democracies to translate public desire into coherent political choices. And we expect elections to deliver these results. But aggregating preferences with elections is harder than it looks. The simplest elections based on innocent design choices will produce paradoxical and confounding results.

In this course, we’ll introduce mathematical and logical tools that can help us understand the paradoxes of elections. You will use these tools to develop and refine your quantitative reasoning skills and apply them to a fundamental problem: how does adding together individual preferences make democracy possible? Topics will include redistricting, voting procedures, and election prediction models. We will look at contemporary examples such as the recent New York City mayoral primary election, and the effect of using districts in choosing the Seattle City Council. You will develop arguments, apply data visualization tools and consider the relevance of statistical reasoning and causal inference.

This section will teach quantitative reasoning and numeracy skills using applications related to elections. Currently, scholars employ a wide variety of quantitative approaches when trying to understand problems of social choice and democratic outcomes. Topics and data examined in this section include those related to campaign finance, redistricting, voting algorithms, voter turnout, polling,  and election fraud analysis.  You will learn the production and interpretation of data visualizations, statistics, and how to design research for causal inference.  You will also gain basic proficiency with Microsoft Excel and RStudio. 

This class discusses political topics but it is not part of the college's political science curriculum. It might leverage your interest in political topics but doesn't require any political knowledge, at all.  We will use politics to demonstrate the power of quantitative reasoning.  
 
## Learning Objectives 

At the conclusion of this course, you will be able to:

* Examine ideas, arguments, biases, and assumptions coming from many perspectives, including your own, with an open yet critical mind. 
* Analyze texts and/or quantitative information, recognizing, describing, and questioning patterns, trends, anomalies, and relationships. 
* Present clear, compelling, and effective arguments and/or analysis, supported by evidence. 
* Critically assess numbers and quantitative data as they are employed by political scientists, pundits, and the media for understanding and predicting political phenomena. 
* Relate issues of diversity, equity, and inclusion to how data is gathered, interpreted, and emphasized. 

### Course Website
https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0?cjc=qdrgoor  
This website will be used for both sections. Google Classroom is one of two sites you will use to submit assignments; the other is My Open Math.  Google Classroom will direct you to the right source for readings and submissions.  This site will also contain all documents and links related to the course.

## Course Administration

### Course Portals

In this course you will access four different portals that require your LC id and password for initial contact.  Google Classroom will direct you from session to session, but you will directed to these sites at different phases of the course.

**My Open Math**  
Readings, videos, and quizzes will be available from My Open Math.  Sign up using the link below.  All material will be directly linked from our class website, so you do not need to regularly check this site directly. 
https://www.myopenmath.com/forms.php?action=enroll
The course ID: 118940
The enrollment key: core121

**Google Classroom**  
In addition to serving as the class website, you will submit papers and your excel labs through Google Classroom. Enroll using this link:
https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0?cjc=qdrgoor

**RStudio**  
You can access RStudio using a web browser and signing in to the college's server at https://datasci.watzek.cloud/.  

In your lab assignments, you will explore datasets, generate data visualizations, and perform simple calculations using the RStudio platform, based on the R programming language.  Dozens of videos and online documents can provide a background explanation of R, and a good place to start is the online manual R for Data Science at https://r4ds.had.co.nz/introduction.html.  

**R Programming for Beginners**
I will introduce you to the R programming language using the RStudio platform.  The goal isn't to achieve mastery of R syntax but rather show you the basic workflow and help you recognize situations when R's power in data management and visualization will help you.  If you want to dive into R, I recommend the R Programming 101 video series in YouTube.  It's entertaining and gentle.

We will have four labs in which you will copy and execute R code in RStudio and report the results. You will also observe the results of changing the code slightly.  For ambitous data visualization projects, you may discover that R can satisfy your requirements better than Excel with a reasonable learning curve.

https://www.youtube.com/watch?v=nRtp7wSEtJA&list=PLtL57Fdbwb_AWmWWrFV_pLqq2uicpUIO9

**Microsoft Excel**    
You will also use Microsoft Excel, an ordinary spreadsheet tool, in labs.  You will gain exposure to spreadsheets, and when you compare the experience to RStudio, you'll see how a scripted programming language has particular advantages and problems compared to spreadsheet applications.

For this purpose, Microsoft Excel is preferred over Google Sheets or other open-source alternatives. Lewis & Clark has a Campus Agreement for Microsoft Office. Because of this, current students, staff and faculty can use their @lclark.edu email address to activate a free Office 365 account, which allows them to use Microsoft apps such as Excel. This program is 100% managed by Microsoft and is completely separate from Lewis & Clark College. 

To set up Office 365:

* Go to https://products.office.com/en-us/student/office-in-education to sign up.
* Enter your Lewis & Clark email address
* Click the Get Started button
* Access the link that is sent to your email to complete the registration
* Follow the prompts to activate Office 365 and create your Microsoft account
* Install Office and sign-in with your newly created Office 365 ID

### Lab Groups  
You will regularly work on labs in groups of 3-4.  

Please fill out this short survey to help me select your Excel and RStudio mates:  https://bit.ly/3iX0tmx.  I will post this survey as an ungraded Google Classroom assignment.  Please complete it by Friday Sep 3.  

### Attendance

Your attendance is expected every class session.  If you can't attend class, please notify me. 

### Laptops and Phones

If you have access to a laptop computer, you *should* bring it to class routinely.

You can bring phones into the classroom, but please note that we have very limited time together and we need to make it count. We all need to be present and free of distraction. I will count on you to do your part.

### Recording Classes  

Lewis & Clark policy generally forbids recording of classes.  The policy states: "...the secret recording (audio or video) of classes, meetings or other conversations, including telephone calls, is prohibited, as not compatible with the law or the promotion of an open exchange of ideas." See me if you have questions.  The policy is available at https://www.lclark.edu/live/profiles/3606-recording-policy.


### Rescheduling Exams  

Notice that the midterm and final exam are scheduled on days that precede college holidays. The exams will take place on those days, and cannot be rescheduled.

### Tutoring at the SQRC  
The Symbolic and Quantitative Resource Center (SQRC) is an informal and free drop-in peer tutoring center. The SQRC will offer both in-person and remote tutoring this semester. In-person tutoring will take place in JR Howard 134 and remote tutoring will take place on the SQRC Discord server. Use this link to join the Discord server: https://discord.gg/VWfT99b

### Changing Sections or Withdrawing  
Any requests to change your Words or Numbers section should be directed to the General Education Office (GenEd@lclark.edu). Because it is a required course designed for first year students, withdrawal is not permitted (unless you are withdrawing from all courses for the semester).

### Diversity, Equity, and Inclusion  
Lewis & Clark and its faculty are committed to diversity, equity, and inclusion in the classroom. I will work hard to ensure that all backgrounds and perspectives thrive in this course.

I am committed to the goal that anyone can achieve mastery of basic quantitative reasoning and the ideas presented in this course. Typecasting ourselves as a "math" or "non-math" person is self-limiting and needless.

If your learning needs are not being met, or you do not feel comfortable with the material being discussed, I am counting on you to let me know.  I will do my best to support a classroom climate that supports a diversity of thoughts, perspectives, and experiences, and that honors your identities (including race, gender, class, religion, ability, etc.). Matters of identity and American politics are inextricably intertwined and as such will be regularly discussed in class and will likely require consideration in your research projects.

### Activities and Grading Formula

The work in this class includes the following:

* Reading ahead of classroom attendance and participation
* Reading, videos, and exercises using the My Open Math platform
* Labs and lab submissions using Microsoft Excel and RStudio
* One 6-8 page paper
* Two group projects

**Two exams: 20% each**\
Each exam is independent and not cumulative (Learning Objectives #2 and #4).  The midterm will take place during the regular class period for Wednesday October 6.  The final exam as scheduled by the university: https://college.lclark.edu/offices/registrar/final_exam_schedule/fall/  

The section 1 final exam takes place on Tuesday, December 14 from 1-4pm in JR Howard 115.
The section 11 final exam takes place on Saturday, December 11 from 1-4pm in JR Howard 253. 

**Research paper & presentation: 20%**  
You are responsible for one 6-8 page paper on a topic related to elections or public opinion that marshals data to provide evidence and includes an original data visualization. In addition, you will present your argument and analysis to the class and answer questions from your colleagues about your analysis. As part of this project, you will need to address how your data and analysis reflects on issues of inclusion, diversity, and equity. (Learning Objectives #2, #3, #4, and #5).

Note that there will be a data visualization contest sponsored by the library, and you're invited to submit your work for that competition. The library will publish details later in the semester.

**Homework/labs: 20%**  
The class will be structured to be participatory, particularly using small groups. This requires everyone to have done the readings and come prepared adequately to critically engage with a variety of arguments, approaches, and data. I will assign periodic activities that will build data literacy, including quizzes, homework, or other assignments. Students will be expected to complete a series of excel-based learning labs, with time devoted to this activity in class. (Learning Objectives #1, #2, #3, #4, and #5) 

**Attendance/ Participation: 5%**  

**Group Projects: 15%**  
There will be two group projects to submit in this course. The output of each project will vary (presentation, written components) and will be explained at the start of each project. You will be graded based on project quality and by peer review.  Significant class time will be devoted to these projects. 

**Late work submissions**
Unless otherwise specified, late work will be penalized by 2/3 of a grade per day.  This means, for example, that an assignment graded as a B will be dropped to C+ the first late day, and to C- the second day.  Work submitted more than 48 hours late will not be accepted.

## Course Schedule  

###  Week 1

#### Monday, August 30  
**Topic:**  A personal course introduction. Syllabus review, a few words about your instructor, and the purpose of CORE121.     

#### Wednesday, September 1   
**Topics:** Reasoning with probability with the Monty Hall Problem, and Manipulating Percentages with Voter Turnout. We will discuss reporting on COVID breakthrough reporting if time permits. 

**Pre-class Homework Assignment #1**:  
Read about the back story of the Monty Hall problem. (No submission but consider the discussion questions before class.)  

**Pre-class Homework Assignment #2:**  
Make sure you have access to the following resources:  
* Create an account with the Office 365 suite and you can access Microsoft Excel.  
* Log into the library's RStudio server at https://datasci.watzek.cloud.  Log in to the main screen then choose RStudio Server on the list that appears next.  
* Register as a new student at myOpenMath.com.  As noted earlier, the Course ID is 118940 and the passcode is core121.
* Make sure you are enrolled in the course portal for Google Classroom. https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0?cjc=qdrgoor  

**Links for the Monty Hall Problem Discussion**  

https://www.businessinsider.com/the-easy-way-to-understand-the-monty-hall-problem-2015-12  
https://www.nytimes.com/1991/07/21/us/behind-monty-hall-s-doors-puzzle-debate-and-answer.html
https://www.vox.com/2015/12/1/9821256/monty-hall-problem-mansplainers

**Links for short articles and Twitter threads on COVID breakthrough cases: If time permits, a conversation:  the basic math of COVID breakthrough cases.**  

https://www.nytimes.com/interactive/2021/08/10/us/covid-breakthrough-infections-vaccines.html   
https://www.nbcnews.com/health/health-news/breakthrough-covid-cases-least-125-000-fully-vaccinated-americans-have-n1275500   
https://twitter.com/JamesSurowiecki/status/1429450130713890824  
https://twitter.com/marynmck/status/1421483545898389504


#### Friday, September 3    
**Topics:**  Manipulating Percentages with Voter Turnout and Introduction to Microsoft Excel.    
**Pre-class Homework Assignment:**  Read pages 1-6 of this textbook chapter and complete the firs three "Try it Now" examples.  

Submit your results in Google Classroom.  
**Links**  
http://www.opentextbookstore.com/mathinsociety/2.5/ProblemSolving.pdf and https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/MzgwMDE4NzU0MjMz/details

**Links for the COVID Breakthrough Percentages Discussion**
https://twitter.com/marynmck/status/1421483545898389504
https://twitter.com/KenDilanianNBC/status/1421208151970533379
https://www.nbcnews.com/health/health-news/breakthrough-covid-cases-least-125-000-fully-vaccinated-americans-have-n1275500

**Survey to match you with your lab mates**  
https://bit.ly/3iX0tmx

###  Week 2

#### Monday, September 6 
No class--Labor Day Holiday

#### Wednesday, September 8    
**Topic:**  Using growth formulas:  artithmetic vs. geometric/exponential growth.    
**Pre-class Homework Assignment #1**:  Read the first 9 pages of PDF (through Example 6, pp. 173-182), and complete the first three "Try it Now" examples.    
http://www.opentextbookstore.com/mathinsociety/2.5/GrowthModels.pdf. 
Submit your results in Google Classroom at https://bit.ly/3mvP679

**Pre-class Homework Assignment #2:** My Open Math Percentage Problem Solving  
https://www.myopenmath.com/assess2/?cid=118940&aid=8515741#/
Enter your results in the My Open Math website. 

#### Friday, September 10    
**Topic:**  Computing inflation and real dollars (Excel Lab) and Introduction to RStudio.  
**Pre-class Homework Assignment #1**:  Skim Excel Lab #1 and watch this short video: https://www.youtube.com/watch?v=y_Nt5BL_wgU.  
**Pre-class Homework Assignment #2:** My Open Math Growth Models https://www.myopenmath.com/course/course.php?cid=118940&folder=0-5k  
**NOTE 9/9: Deadline for this assignment moved to end-of-day on Monday 9/13 (shown below)**   
**In class Lab:**  Excel Lab 1, Part 1 (Turnout) https://bit.ly/3yO3PN3
**Other**:  We will finalize lab groups for the semester 


### Week 3

#### Monday, September 13     
**Topic:**   
Excel lab (Campaign Finance): Computation from simple data in Excel. Today we will form into groups and work on the Excel Lab #1.  

Class today will continue work on the Excel lab. Submit the spreadsheet (whatever you have) before class on Wednesday, even if you don't finish it.

**Pre-class Homework Assignment** My Open Math Growth Models https://www.myopenmath.com/course/course.php?cid=118940&folder=0-5 NOTE 9/9: Deadline moved to from Friday 9/10. 

#### Wednesday, September 15  
**Topics:**  
Statistics, the difference between Statistics vs. Mathematics. 
An introduction to R and RStudio.  
Link to RStudio Lab 1:  https://core121-election-science-fall2021.netlify.app/core121-lab-1-v1

**Pre-class Homework Assignment #1**:  
Read Pages 1-11 in  http://www.opentextbookstore.com/mathinsociety/2.5/Statistics.pdf  
**Submit Excel Lab #1:**  Excel Lab, parts 1 and 2. Everybody submit your own copy of the assignment even though you collaborated.  https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/Mzc5OTM1Njk2MDE4/details

#### Friday, September 17  
**Topic:**  Introduction to Surveys using statistical inference.  

**Pre-class Homework Assignment #1**:  Before class, read https://www.nytimes.com/2020/11/10/upshot/polls-what-went-wrong.html (PDF here: https://drive.google.com/file/d/1HKM5UQzn3F1WkuURYjzzkEbepdumG_Qj/view?usp=sharing)  
This is an update to the link which posted on 9/16

**Submit RStudio Lab #1**  
RStudio Lab 1 (Submit your completed results described in the lab.)  https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/Mzc5OTM1Njk2MTEx/details. Note: the goal isn't to master R syntax. You will simply copy, paste, and run R code, and you'll get the hang of the RStudio workflow.

###  Week 4

#### Monday, September 20  
**Topic:**  
Data organization:  observations, variables, and description.  

**Pre-class Homework Assignment:**  
Review of datasets suitable for class projects, and you will identify datasets of potential interest.  Come to class prepared with a preliminary list.  Submit your preliminary list here:  https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/MzgwMDIxNzE5NDM4/details


#### Wednesday, September 22  
**Topic:**   
Data organization:  observations, variables, and description   
**Pre-class Homework Assignment #1**:  

Read http://www.opentextbookstore.com/mathinsociety/2.5/DescribingData.pdf pp. 247-269.  Complete the eight "Try it Now" examples and submit to Google Classroom. https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/Mzc5OTc4MTQ1Nzg1/details

**Pre-class Homework Assignment #2:** Watch this 7:47 minute video. https://www.youtube.com/watch?v=Kno1gJiO5Dg  

#### Friday, September 24  

**Topic:**  
Creating data tables with Excel and RStudio.  This class session will cover lab material.

**Pre-class Homework Assignment #1**:  
Review Excel Lab 2 which will begin during class. 

**Pre-class Homework Assignment #2:** 
My Open Math: Collecting Data  
https://www.myopenmath.com/course/course.php?cid=118940&folder=0-6&r=6116fc9cd5bcf Complete the exercises in the myOpenMath site.
The Google Classroom assignment record is here:  https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/MzgwMDIxNzM5MzU5/details

### Week 5

#### Monday, September 27  
**Topic:**  
Creating and using data tables with Excel.

**Pre-class Homework Assignment #1**:  Watch this R Programming 101 video (6:55 in length). 
A short exercise with RStudio is assigned.  Simply transcribe and run the code statements mentioned in the video (about a dozen lines.)
https://www.youtube.com/watch?v=nRtp7wSEtJA&list=PLtL57Fdbwb_AWmWWrFV_pLqq2uicpUIO9.

We will work on Excel Lab #2 exclusively, following a short explanation of survey weights.


#### Wednesday, September 29  

**Topic:**  
Variation and the Standard Deviation  

**Pre-class Reading Assignment:**  https://seeing-theory.brown.edu/probability-distributions/index.html Read through the interactive online chapters from Chapter 1: Basic Probability to Chapter 5: Bayesian Inference. 
Note:  No Google homework assignment for this reading.  

**Excel Lab Due:**  Excel Lab 2 https://bit.ly/3zaucxS

#### Friday, October 1  

**Topic:**  
Review of the study guide for the midterm exam.


Note:  No Google Classroom assignment for this reading.
UPDATE 9/22:  The originally scheduled RStudio lab is postponed and its status will be announced after the fall break.


### Week 6

#### Monday, October 4  
**Topic:**  
Confidence Intervals and Margins of Error in the Normal Distribution (with more review for the midterm exam.)


**Pre-class Reading Assignments:** 
Read https://www.statisticshowto.com/probability-and-statistics/hypothesis-testing/margin-of-error/
Read https://myopenmaths3.s3.amazonaws.com/cfiles/29937/MAT14xTextbook1stEditionCh12.pdf (pp. 1-5) AND https://myopenmaths3.s3.amazonaws.com/cfiles/2408/ReadingE8.pdf (pp. 1-4)
Note:  No Google Classroom assignment for this reading.


#### Wednesday, October 6
Midterm Exam 

#### Friday, October 8
No class--Fall Break.

### Week 7

#### Monday, October 11 

**Topic:**  
Voting Theory Part 1  

**Pre-class Homework Assignment:**  Read http://www.opentextbookstore.com/mathinsociety/2.5/VotingTheory.pdf (pp. 35-43) and plan to submit Try It Now question answers due Friday October 15.  See that date below for Google Classroom link.  

#### Wednesday, October 13 

**Topic:**  
Ranked Choice Voting and the New York Mayoral Primary

#### Friday, October 15   
**Topic:**  Voting Theory Exercise Workshop

Plan to complete the Try it Now Exercises 1-3 from Monday's reading. Submit to Google Classroom https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/MzgwMDIyOTc5NDg1/details

### Week 8

#### Monday, October 18 

**Topic:** Voting Systems (continued)
We will review the voting systems mentioned in the Voting Theory reading, including Plurality, Borda, Copeland, and Approval Voting,  

**Assignment Due Next Monday**
From the apportionment reading, complete Exercises 7 and 8 using the Webster method and the Huntington-Hill method. Submit using the link below. 

The reading can be found at http://www.opentextbookstore.com/mathinsociety/2.5/Apportionment.pdf

#### Wednesday, October 20 
 
**Topic:**  
Apportionment and the U.S. House of Representatives.   

**Pre-class Reading Assignment**  
http://www.opentextbookstore.com/mathinsociety/2.5/Apportionment.pdf
We will examine the different apportionment methoods mentioned in this article, focusing on Webster and Huntington-Hill.

#### Friday, October 22

**Topics:**  
Your Data Project and Presentation. 
Apportionment and the U.S. House of Representatives:  Webster and Huntington-Hill methods.

We will discuss the end-of-semester data projects, which include a presentation and a short paper.  The presentations will cover the final five days of class, and the paper (6-8 pages) is due Wednesday, December 8.

**Pre-class Reading Assignment**:  
Read https://www.ianrmcdonald.com/posts/2021-05-10-new-york-and-house-apportionment-in-2020_update/ 

### Week 9

#### Monday, October 25   

**Topic:**  Gerrymandering in the United States and the Group Voting Rules project.  

Read https://www.quantamagazine.org/the-math-behind-gerrymandering-and-wasted-votes-20171012/ and come prepared to discuss this question:    

"What is the definition of gerrymandering, and how can we use the efficiency gap to measure it?"

We will also assign the voting systems group project.  Your group will be responsible for defining the outcome of the New York mayoral primary using Approval Voting. You will apply a common dataset to the project.  The submission is due Monday, November 8.

Apportionment Assignment Due. https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/MzgwMDI0MDExNjU3/details

#### Wednesday, October 27

**Topic:**  

Gerrymandering and the politics of geography:  More on the efficiency gap, measuring gerrymandering, and Seattle City Council Switches to Districts  

**Preclass Reading Assignment:** 

Read https://sccinsight.com/2021/03/19/understanding-the-city-council-redistricting-process/ and come prepared to answer this question:  "Why would Seattle voters have chosen to adopt a district based system in 2013, given all the uncertainty about managing and defining districts?  Isn't that going backwards?"


#### Friday, October 29  
**Topic:**   

The implications of district building with Dave's Redistricting tool and District Builder.  

**Preclass Reading and Video Assignment:**   

Watch this video (13:38 minutes):  https://www.youtube.com/watch?v=Pp42Rw2cVQA and peruse the online tool at https://davesredistricting.org/maps#home  
We will compare this tool to https://www.districtbuilder.org/ if time permits

### Week 10

#### Monday, November 1 

**Topic:**  

In-class Excel Lab:  Voting systems and data visualization (submit results in class)

#### Monday, November 3

**Topic:** Data visualization:  Principles of data visualization.  We will also review the remaining semester schedule. 

**Preclass Reading Assignment:** 

Read https://fivethirtyeight.com/features/the-52-best-and-weirdest-charts-we-made-in-2016/ 

Read https://www.livescience.com/45083-misleading-gun-death-chart.html

#### Friday, November 5 
**Topic:**  Data Visualization:  Applying Principles of Data Visualization

**Preclass Reading Assignment:**  Read https://towardsdatascience.com/data-visualization-101-7-steps-for-effective-visualizations-491a17d974de 

Look at this overview of an app called datawrapper.  We will use this application to build maps for the lab due on November 15:  https://www.datawrapper.de/maps

### Week 11

#### Monday, November 8 

**Topic:**  Using District Building and Dave's Redistricing Tool

**Group Project Due** Voting Systems. https://bit.ly/3zmK5kP

**Preclass Assignment:** 
A reminder to watch this video that appeared in the syllabus for October 29:

Watch this video (13:38 minutes):  https://www.youtube.com/watch?v=Pp42Rw2cVQA and peruse the online tool at https://davesredistricting.org/maps#home  
We will compare this tool to https://www.districtbuilder.org/ if time permits

**Review Redistricting Tool Builder** on Data Visualization https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/Mzg0NTk2NDY0NTcz/details
This lab is due Monday, November 15.

#### Wednesday, November 10 

**Topic:**  Group Project #2: Redistricting
We will organize this group project, analyzing efficiency gap of different districting plans.  This project will be due Monday, November 22.

#### Friday, November 12 

**Topic:** Data project workshop.

### Week 12

#### Monday, November 15

**Topic:**  The U.S. Electoral College

**Preclass Reading Assignment:** 

Read https://www.nytimes.com/article/the-electoral-college.html AND https://www.nationalpopularvote.com/written-explanation. 

Come prepared to answer this question:  "Maine and Nebraska don't use winner-take-all allocations of their electors.  Why don't the other 48 states and DC follow their lead?"

Excel Data Visualization Lab Due.  https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/Mzg0NTk2NDY0NTcz/details

#### Wednesday, November 17   

**Topic:**  
Electoral College and American Politics

**Pre-class Reading Assignment:**  Read this article: Mason, Lilliana. 2018.  Losing Common Ground: Social Sorting and Polarization *The Forum* v.18(1) https://bit.ly/3go9bZa

#### Friday, November 19  
**Topic:**  Data projects workshops.  

We will work on data projects.  Presentations will begin November 24.   

### Week 13

#### Monday, November 22  
**Topic:**  In-Class Review Session and Preparation for Presentations

Group Project Due: Redistricting Project.  Submit your work here: https://bit.ly/3D8gv4K 

#### Wednesday, November 24   
Presentations

#### Friday, November 26
No Class:  U.S. Thanksgiving Holiday 

### Week 14

#### Monday, November 29  
Presentations

#### Wednesday, December 1  
Presentations

#### Friday, December 3  
Presentations

### Week 15

#### Monday, December 6  
Presentations

#### Wednesday, December 8  
Final Exam Review

### Week 16

#### Saturday, December 11    
Section 11 Final Exam: 1-4pm  

#### Tuesday, December 14  
Section 1 Final Exam:  1-4pm


Read https://www.nytimes.com/2021/06/24/opinion/ranked-choice-new-york.html?referringSource=articleShare 

AND 

https://www.washingtonpost.com/opinions/2021/07/07/eric-adams-new-york-mayor-ranked-choice-voting-worked/  

Come prepared to answer this question: "How did New York's attempt at Ranked Choice Voting affect the race, even though the plurality winner, Eric Adams, was ultimately the winner of the Democratic primary?"  In New York City, his primary victory makes Adams the presumptive winner of the mayoral election in November. 
